### ISSUE TITLE
How to accomplish this with the latest Angular 2?

### ISSUE THREAD

**Issue by thardy-pd** [IEvangelist/MvcAngular2#2]
AsyncRoute has been deprecated and I am looking for a way to accomplish what your example here does using the latest version of Angular 2.  I'm having trouble in my search to see exactly what has replaced AsyncRoute.  I really want to be able to use Mvc to render the templateUrl for a component.

Do you know how to accomplish the same thing in the latest version of Angular 2?  Any tips or links will be greatly appreciated.

**Comment by IEvangelist** [comment]
I plan on creating another new repo to replace this one, as it is an entire re-write. I will then blog about it in detail. With the latest **Angular2** it cannot be done.
